### ISSUE TITLE
submodule in the fx2lib for the cypress firmware

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#108]
The Makefile should do something like;

``` Makefile
fx2lib/Makefile:
    git submodule --init
    git submodule --update

fx2lib/lib/xxxxx: fx2lib/Makefile
    cd fx2lib; make

```

**Comment by shenki** [comment]
https://github.com/shenki/HDMI2USB/commit/111d12236d2069e7f51063b24d56a8f10f689ce1

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
