### ISSUE TITLE
cypress firmware makefile should put build artificat in an ./cypress/output directory

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#110]

**Comment by shenki** [comment]
I am happy with the existing behaviour

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
