### ISSUE TITLE
Merge rohit's changes for correct usbid changes from old libfpgalink

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#111]
https://github.com/timvideos/HDMI2USB/wiki/USB-IDs
https://github.com/rohit91/libfpgalink/commits/hdmi2usb
https://github.com/timvideos/HDMI2USB/issues/47

```
Rohit Kumar Singh
Correct errors in README
rohit91 authored 6 days ago

28b6517  
 Rohit Kumar Singh
Added eeprom IIC file and README
rohit91 authored 6 days ago

4de8948  
 Rohit Kumar Singh
Makefile modified to make the firmware appear as HDMI2USB Configured … …
rohit91 authored 6 days ago

474c64c  
Commits on Jan 9, 2015
Rohit Kumar Singh
Modified README.md
rohit91 authored 8 days ago

71617a5  
 Rohit Kumar Singh
Firmware working now
rohit91 authored 8 days ago

7f84b46  
```

**Comment by shenki** [comment]
All commits present as of https://github.com/shenki/HDMI2USB/commit/3902ded7bfae520afcde8d75eb7addc8170d6d15

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
