### ISSUE TITLE
keep streaming something when hdmi input drops

### ISSUE THREAD

**Issue by CarlFK** [timvideos/HDMI2USB-jahanzeb-firmware#121]
The device should always stream (send video data over usb)  something.
if the hdmi signal drops or is invalid or whatever, something should be sent. 
test pattern, static "invalid signal", last frame, .. anything.  

Otherwise the recording and live stream systems have to contend with this state, and that's hard.

**Comment by mithro** [comment]
The new [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) doesn't suffer from these problems.
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
