### ISSUE TITLE
Make 720p the default

### ISSUE THREAD

**Issue by CarlFK** [timvideos/HDMI2USB-jahanzeb-firmware#124]
16:9 is more popular than 4:3, so it would be good if that was the default.

**Comment by mithro** [comment]
The new [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) does this.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
