### ISSUE TITLE
Support the Numato Opsis board

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#130]
The [Numato](http://numato.com) Opsis board is the first [HDMI2USB](http://hdmi2usb.tv)
production board developed in conjugation with the [TimVideos.us](http://code.timvideos.us) project. 

It's features include;
- 2 x HDMI input ports,
- 2 x HDMI output ports,
- DisplayPort input and output ports,
- 128Mbit DDR3-1600 ram,
- Gigabit Ethernet with MAC address EEPROM,
- Micro SD card,
- Cypress FX2 for USB device functionality,
- ULPI for USB OTG functionality,
- Quad speed SPI flash.

Sample code for the Opsis can be found at https://github.com/mithro/numato-opsis-sample-code

**Comment by vitecd** [comment]
Hi
Unfortunately I can't found any notes about 'opsis' at Numato Web site

**Comment by mithro** [comment]
@vitecd - The opsis board is not yet available for purchase as we are still in the initial bring up stage (and already have discovered a couple of very small bugs with the design that we wish to fix before beginning full scale production).  We want to verify the firmware works with the board before announcing it officially.

The board schematic and PCB design _will_ be publish shortly (maybe later today depending on how things go). Will keep you informed.

**Comment by mithro** [comment]
The Numato Opsis board is now crowdfunding at https://www.crowdsupply.com/numato-lab/opsis
The board is also supported by the misoc based firmware - https://github.com/timvideos/HDMI2USB-misoc-firmware

**Comment by mithro** [comment]
With the misoc firmware already being in a much better state - we won't be porting this firmware to the Opsis board.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
