### ISSUE TITLE
docs: makestuff.eu has been taken over by a squatter

### ISSUE THREAD

**Issue by micolous** [timvideos/HDMI2USB-jahanzeb-firmware#131]
All the docs that reference makestuff.eu need to be amended, as the domain name has been taken over by a squatter.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
