### ISSUE TITLE
docs: fxload is missing

### ISSUE THREAD

**Issue by micolous** [timvideos/HDMI2USB-jahanzeb-firmware#132]
Also reported by a user here: http://list.waikato.ac.nz/pipermail/wlug/2015-September/013789.html

This repository is gone: https://github.com/pbatard/fxload

It appears to have been a private fork of fxload, and not part of the upstream project at all.

This is referenced by the documentation as one of the two ways to program stage 2 of the HDMI2USB firmware, which is blocked also because the alternate tool is also not available.

If you have a backup, put it in the timvideos organisation on github, or document an alternative tool.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
