### ISSUE TITLE
Look at supporting Marvell Ethernet chip on Digilent board

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#14]
Use instead of USB

**Comment by mithro** [comment]
Some of the things linked from https://twitter.com/michaelossmann/status/302581047940505600 might be useful.

**Comment by mithro** [comment]
- The BitHound uses the Atlys board and supports Ethernet
  - http://www.bastli.ethz.ch/index.php?page=BitHoundEn
  - Find the firmware at [BitHound_ATLYS_2.1.zip](http://www.bastli.ethz.ch/BitHounddata/BitHound_ATLYS_2.1.zip). Look in the V2.1/fpga/mac/ directory.
- Joel Williams has created a partially working core at http://www.joelw.id.au/FPGA/DigilentAtlysResources
- USRP2 uses a different ethernet chip, but contains a working GPL licensed gigabit-only MAC and MDIO interface core
  - https://github.com/EttusResearch/uhd/tree/master/fpga/usrp2/simple_gemac
  - https://github.com/EttusResearch/uhd/tree/master/fpga/usrp2/udp
- Alternative approach would be an aemb / Microblazed based system
  - http://opencores.org/project,aemb
- OpenCores has an Ethernet MAC at http://www.opencores.org/projects/ethmac/

**Comment by mithro** [comment]
Tariq has been working on this project as part of Google Summer of Code 2014. You can see his progress on this project at http://hdmi2ethernet.blogspot.com.au/

**Comment by mithro** [comment]
@tariq786 @cfelton Can you give a final update on your progress with this stuff?

I think we should then probably close this issue and open some more specific issues around the problems you found.

**Comment by tariq786** [comment]
@mithro 

Does the following help

http://bit.ly/1rydWx6
http://bit.ly/1jc1wFk

They are both listed in the 2nd last entry in the blog

http://hdmi2ethernet.blogspot.com.au/2014/08/final-report-and-almost-finished.html

**Comment by mithro** [comment]
This is supported in the new misoc based firmware at https://github.com/timvideos/HDMI2USB-misoc-firmware

The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
