### ISSUE TITLE
Investigate (and hopefully mitigate) JPEG block boundary artifacts on fine text detail

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#17]
When a vertical line is on a block boundary, JPEG can sometimes discard the whole line - this is mostly apparent on fine text capture.

Investigate ways to mitigate this problem and add tests to prevent this problem from reoccurring.

**Comment by mithro** [comment]
@ajitmathew - Can you investigate this? Is there anything we can do?

**Comment by cfelton** [comment]
How is this problem being observed?  Is it noticed in the output (once the frame is uncompressed) or is the error detected, some how, in the design?  From my understanding this should not occur.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
