### ISSUE TITLE
Add support for low frame rate "raw" capture.

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#18]
Since we now capturing the whole frames into RAM, it should be possible to ship up raw frames at a low frame rate to the system.

I believe the UVC spec supports raw YUV and RGB frames.

**Comment by jahanzeb** [comment]
YUYV support added.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
