### ISSUE TITLE
HDMI2USB should work without a display.

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#21]
The HDMI2USB should appear as a display to the computer, even when there is no display plugged into it.

**Comment by jahanzeb** [comment]
Yes that is correct. It does appear as display to computer even when there is not display plugged in.

**Comment by mithro** [comment]
It'll capture correctly too?

**Comment by jahanzeb** [comment]
yes, will capture with no problems.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
