### ISSUE TITLE
Onboard video manipulation

### ISSUE THREAD

**Issue by CarlFK** [timvideos/HDMI2USB-jahanzeb-firmware#22]
Sometimes presenters display has poor color choices, like white text on grey background.  

Inverting the display can dramatically improve the readability.  I am guessing there are some other simple changes that could be implemented. like dropping color depth or gray scale?

**Comment by jahanzeb** [comment]
Gray scale is already implemented use SW[1] to toggle between color and gray scale. 
other simple things are also possible like dropping a color or two colors or swapping colors these are very simple to implement.

**Comment by mithro** [comment]
Added labels.

**Comment by mithro** [comment]
We should add support for changing that filtering via a the USB comport.

This is low priority however.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
