### ISSUE TITLE
CDC device endpoint doesn't work under Linux

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#23]
After loading the hdmi2usb.hex from `Drop Box/freelancehandover/cypress/uvc+cdc/output/hdmi2usb.hex`

The CDC port doesn't work under Linux, it has the following error in `dmesg`

```
[2324637.624638] cdc_acm 2-1.2.2:1.2: This device cannot do calls on its own. It is not a modem.
[2324637.624648] cdc_acm: probe of 2-1.2.2:1.2 failed with error -22
```

**Comment by jahanzeb** [comment]
fixed and tested.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
