### ISSUE TITLE
Latest firmware gives black image

### ISSUE THREAD

**Issue by micolous** [timvideos/HDMI2USB-jahanzeb-firmware#28]
Latest firmware from here gives a black image:

https://www.dropbox.com/sh/s5zw70u754lpbmv/N95myLaoJT

```
91da91a4eada6a72c1dedf02d3d732ee771b5535  hdmi2usb.bit
5a5cf80748633448eaecf3d0b88ec50015034153  hdmi2usb.hex
```

"Archive" MJPEG firmware gives correct image:

```
e540d3210f7c2fc71d1427c0e12528a86aeae525  hdmi2usb_mjpeg.bit
ce380c747052530198c134527392c1c466dd6448  hdmi2usb_mjpeg.hex
```

LEDs LD7 - LD0 show: on on on dim off off off on

Pressing UP changes LEDs to show: off off on dim off off off on

**Comment by jahanzeb** [comment]
black image might be because of incorrect resolution
use

luvcview -f MJPG -s 1024x768

luvcview -f YUYV -s 1024x768

for correct image.

**Comment by jahanzeb** [comment]
LED 2 is off means you are trying to read raw and there is no image size
information in raw so it expects fix bytes.
i am guessing you are using VLC because i had the same problem with VLC.
to correct this in VLC you need to define the video size 1024x768.

**Comment by jahanzeb** [comment]
are you using fxload or fx2loader to configure the cypress chip? if yes can you test the firmware before using it by serial communication with the board. send SS to ttyACM0 and see if you get two bytes in return if you are getting random bytes then cypress chip is not programmed properly.

**Comment by mithro** [comment]
Using lucview as documented in the README file.

Tim

**Comment by micolous** [comment]
I was using luvcview invoked identically for both tests... `luvcview -f MJPG -s 1024x768 -d /dev/video1`.

I'm using `fxload` to program the chip.  Unfortunately will have to wait to test it out on the board again as I'm not in a position to verify it now.

**Comment by jahanzeb** [comment]
Bug fixed and new repository for prebuild created as suggested by tim.

**Comment by micolous** [comment]
Confirming that https://github.com/jahanzeb/HDMI2USB_prebuild/commit/d704b9cfaf9a92994d23287b10d8901e492528f7 in jahanzeb/HDMI2USB_prebuild resolves my issue, thanks.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
