### ISSUE TITLE
Heartbeat on static images

### ISSUE THREAD

**Issue by CarlFK** [timvideos/HDMI2USB-jahanzeb-firmware#31]
If the display is static, it is hard to tell if everything is functioning.  

it would be handy (maybe?) to be able to enable something dynamic that can be checked for.  maybe even 1 pixel, or small block in the corner that pulses.

**Comment by mithro** [comment]
@CarlFK did you verify this works? If so, lets close this issue.

**Comment by mithro** [comment]
Fixed.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
