### ISSUE TITLE
Optimisation MJPEG to support atleast 720p@30fps

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#32]
Optimisation of the MJPEG core in the HDMI2USB firmware to support full frame rate recording.

Current performance is roughly `720p@15fps` minimum requirement would be `720p@30fps`. We'd really like it to reach somewhere between `1080p@30Hz` --> `1080p@120Hz`.

The current HDMI2USB core was generated from the [mkjpeg project at OpenCores](http://opencores.org/project,mkjpeg) and found at [hdl/jpeg_encoder code](https://github.com/timvideos/HDMI2USB/tree/master/hdl/jpeg_encoder).

**Comment by mithro** [comment]
Ajit has been working on this as part of Google Summer of Code 2014 and made some interesting progress.

You can see his initial proposal at
https://docs.google.com/a/mithis.com/document/d/1akF6lBb78OWTGFosnYUC5-MxuNZXCrCob70ga3uQB8A/edit

You can see his initial report which was part of his proposal at
https://docs.google.com/a/mithis.com/document/d/1pCYF79ujko-1JQ2qbcrGXK5mKaGU1qsFsZwuKfJ2Ku8/edit

You can see his mid-term report (from a couple of weeks ago) at
https://docs.google.com/a/mithis.com/document/d/1YwD7ZuVogUXlRbBu8hCpQkHv_tboYZGei7_H4wEErDg/edit

There is also a lot of information on his blog at http://ajitmathewgsoc.blogspot.com.au/2014/07/plans.html

**Comment by mithro** [comment]
@ajitmathew Can you give this issue a status update? I believe this has been finished?

**Comment by ajitmathew** [comment]
We are getting 30 fps for 50% encoding and for higher encoding frame rate
depends on the image. To get 30fps for other encoding quality we need to
improve the USB bandwidth.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
