### ISSUE TITLE
Make the "test" image nicer.

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#33]
The HDMI2USB inputs can be switched to a test image. It would be nice if this image was prettier and/or had some type animation in it.

**Comment by mithro** [comment]
@rohit91 did some work to make the test image nicer, it was merged in the above pull request.

**Comment by mithro** [comment]
@rohit91 What is the current test image status?

We should figure out if there is anything more we want to add to the test image and if not close this bug.

**Comment by CarlFK** [comment]
I think the new color bars are fine.  There can be more test images and such in the future, but this is not a blocker to running in production.  

close this out, someone may do some other sort of test pattern, but we don't need a open issue for it.

**Comment by rohitk-singh** [comment]
I second that. If any different patterns types in future are desired I will add them too!

**Comment by mithro** [comment]
This bug was only left open to confirm that the new colored bars where working and usable after merging @rohit91's change. If @CarlFK thinks they are fine, then I think we can close this issue for more specific issues around making useful test patterns for testing.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
