### ISSUE TITLE
Resolve warnings in firmware build

### ISSUE THREAD

**Issue by shenki** [timvideos/HDMI2USB-jahanzeb-firmware#38]
The build currently contains a large number of warnings:

```
  Number of warnings: 341
```

These should be fixed, or suppressed.

**Comment by ktovletoglou** [comment]
There are 341 Warnings in the translation process. Most of them are warnings of the type "Logical net has no driver", these can be corrected by setting the property "Keep Hierarchy" to false

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
