### ISSUE TITLE
Implement HDMI matrix/switching functionality

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#4]
Two HDMI inputs, two HDMI outputs.

Control which input goes to which output via both:
- D-Pad control
- CDC Commport

**Comment by jahanzeb** [comment]
2x1 Hdmi matrix. one output is duplicated to both hdmi output ports.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
