### ISSUE TITLE
Connect the USB-UART connector to the control system inside the firmware

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#44]
We have a "control port" which appears via the USB PROG port as a "usb serial port".

The Atlys board also has a "USB-UART" connect. It would be nice if the control port was also connected to this. Allowing control / debugging of the system when the Cypress firmware programming fails.

http://www.digilentinc.com/Data/Products/ATLYS/Atlys_ISE_GPIO_UART.zip

**Comment by mithro** [comment]
@ajitmathew This has been done right? Can we close it?

**Comment by ajitmathew** [comment]
This is not fully functional. Some more work is required.

**Comment by mithro** [comment]
Can you please put the current status in this issue?

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
