### ISSUE TITLE
Board not accepting USB device number

### ISSUE THREAD

**Issue by puck** [timvideos/HDMI2USB-jahanzeb-firmware#45]
After l've followed the instructions on:
https://github.com/timvideos/HDMI2USB/wiki/Digilent-Atlys-Board:-Loading-Firmware
Up to Stage 3, step 3, when I plug the USB cable back into the PROG port, on my Linux box I get:

[8552952.824097] usb 1-1.6.2: new full-speed USB device number 120 using ehci-pci
[8552953.243713] usb 1-1.6.2: device not accepting address 120, error -32
[8552953.243830] hub 1-1.6:1.0: unable to enumerate USB device on port 2

The HDMI2USB test screen is output on the HDMI OUT, and if I plug in a PC to an HDMI IN port, I can select the input which is correctly displayed on HDMI OUT.

I've tried plugging the USB into a screen connected to my PC, and into a laptop. USB devices on my PC:

Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 045e:0750 Microsoft Corp. Wired Keyboard 600
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 059: ID 04b4:6560 Cypress Semiconductor Corp. CY7C65640 USB-2.0 "TetraHub"
Bus 001 Device 072: ID 045e:0024 Microsoft Corp. Trackball Explorer
Bus 001 Device 071: ID 04b4:6560 Cypress Semiconductor Corp. CY7C65640 USB-2.0 "TetraHub"
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Firmware is commit 2ddc2c7cf4326bd860e0e4f30206b2d49093873b in the HDMI2USB-firmware-prebuilt git repo.

**Comment by puck** [comment]
I've also tried plugging it directly into my PC, same issue.

**Comment by mithro** [comment]
Can you include the kernel + distro information.

Plus the fxload version info (-V and dpkg info) and the Digilent Tools version info.

**Comment by puck** [comment]
And I just tried the 20130709 binaries.

**Comment by puck** [comment]
Sorry. Debian Sid, kernel 3.10.27-vs2.3.6.8-beng (there is a 3.13 kernel I can try).

I've tried both fxload from Debian Sid - 0.0.20081013 and fxload from https://github.com/pbatard/fxload .

Digilent tools: digilent.adept.utilities_2.1.1-x86_64

**Comment by mithro** [comment]
Anything on your Atlys board that identifies it? Anything like board revision number or similar would be good.
Can you include your Atlys serial number too?

**Comment by puck** [comment]
The Atuys board is a Spartan-6, revision C. Two stickers on the understand one has D501089 and other looks like a MAC address, 00183E017C0B.

**Comment by mithro** [comment]
Can you download "lsusb.py" from https://github.com/gregkh/usbutils/blob/master/lsusb.py and send the output? (You might need to get /usr/share/usb.ids from http://www.linux-usb.org/usb-ids.html)

**Comment by puck** [comment]
Sure:

```
usb1             1d6b:0002 09  2.00  480MBit/s 0mA 1IF  (ehci_hcd 0000:00:1a.0) hub
 1-1             8087:0024 09  2.00  480MBit/s 0mA 1IF  (Intel Corp. Integrated Rate Matching Hub) hub
  1-1.5          04b4:6560 09  2.00  480MBit/s 100mA 1IF  (Cypress Semiconductor Corp. CY7C65640 USB-2.0 "TetraHub") hub
   1-1.5.1       045e:0024 00  1.10  1.5MBit/s 100mA 1IF  (Microsoft Microsoft Trackball Explorer®)
  1-1.6          04b4:6560 09  2.00  480MBit/s 100mA 1IF  (Cypress Semiconductor Corp. CY7C65640 USB-2.0 "TetraHub") hub
usb2             1d6b:0002 09  2.00  480MBit/s 0mA 1IF  (xhci_hcd 0000:03:00.0) hub
 2-1             045e:0750 00  1.10  1.5MBit/s 100mA 2IFs (Microsoft Wired Keyboard 600)
usb3             1d6b:0003 09  3.00 5000MBit/s 0mA 1IF  (xhci_hcd 0000:03:00.0) hub
usb4             1d6b:0002 09  2.00  480MBit/s 0mA 1IF  (ehci_hcd 0000:00:1d.0) hub
 4-1             8087:0024 09  2.00  480MBit/s 0mA 1IF  (Intel Corp. Integrated Rate Matching Hub) hub
```

**Comment by mithro** [comment]
Can you give me the output when the board is connected but you haven't flashed it yet?

**Comment by puck** [comment]
Sure:

```
[8568392.064405] usb 4-1.1: new high-speed USB device number 25 using ehci-pci
[8568392.174657] usb 4-1.1: config 1 interface 0 altsetting 0 bulk endpoint 0x1 has invalid maxpacket 64
[8568392.174663] usb 4-1.1: config 1 interface 0 altsetting 0 bulk endpoint 0x81 has invalid maxpacket 64
[8568392.176604] usb 4-1.1: string descriptor 0 read error: -32
[8568392.176610] usb 4-1.1: New USB device found, idVendor=1443, idProduct=0007
[8568392.176614] usb 4-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
```

**Comment by mithro** [comment]
Sorry, I should have been more specific.

Can you get me the output of the lsusb.py tool when the board is connected but you haven't flashed it yet?

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
