### ISSUE TITLE
Get real VID:PID values for HDMI2USB project

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#47]
Currently we are using a VID:PID that was chosen randomly, this is probably bad.

From http://www.oshwa.org/2013/11/19/new-faq-on-usb-vendor-id-and-product-id/

> USB vendor IDs (VID) and product IDs (PID) are 16-bit numbers used to identify USB devices to a computer or other host. Each vendor ID is assigned by the USB Implementers Forum to a specific company, which in turn assign a PID to individual products. The VID and PID are then embedded in the product and communicated to the computer when the device is plugged in, along with text strings describing the vendor and product and additional descriptors about the communication protocols supported by the device.

Options appear to be;

> If you’re using an off-the-shelf chip for USB communication, you may be able to use the VID/PID of that chip (e.g. [with FTDI chips](http://www.ftdichip.com/Support/Knowledgebase/index.html?caniuseftdisvidformypr.htm)). [OpenMoko](http://www.openmoko.com) has [opened up their VID](http://wiki.openmoko.org/wiki/USB_Product_IDs) for use by free and open-source software and hardware communities. Here’s [one attempt to get a VID for open-source projects](http://www.arachnidlabs.com/blog/2013/10/18/usb-if-no-vid-for-open-source/). Ian Lesnet also gave a good&nbsp;[talk on the USB VID/PID situation](http://vimeo.com/63986266) ([slides](http://2012.oshwa.org/files/2012/07/USBID-v1.1-oct9.pdf)) at the 2012 Open Hardware Summit.

**Comment by mithro** [comment]
https://github.com/timvideos/HDMI2USB/wiki/USB-IDs

**Comment by shenki** [comment]
Fixed as of https://github.com/shenki/HDMI2USB/commit/3902ded7bfae520afcde8d75eb7addc8170d6d15

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
