### ISSUE TITLE
Create replacement HDMI extension board which has DVI or HDMI connectors

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#5]
The http://digilentinc.com/Products/Detail.cfm?NavPath=2,648,870&Prod=VMOD-MIB adds another 4 HDMI ports to the Digilent board, but they are the HDMI-Micro-D connectors which are hard to get cables for.

Would be awesome to create a version which has HDMI or DVI connectors instead.

**Comment by mithro** [comment]
@rohit91 Do you think you could give this a go? Should be a pretty simple board right?

You already have the VHDCI connector footprint, right? We should probably use the following HDMI connectors -> https://github.com/mithro/timvideos-edid-injector#connectors

We should use the HDMI connectors documented at -> https://docs.google.com/a/mithis.com/spreadsheets/d/1f-rBfR98f_ZZNIB7GFV79CGSHQNpj47uOU0JDwOJnV8/edit?usp=drive_web

The Digilent board doesn't have any ESD protection, we might want to add that too?

Would be nice if this board was auto-detectable, but I don't think there are any pins left? Maybe breaking it out to a PMOD header or an I2C multiplexer would work?

**Comment by rohitk-singh** [comment]
It is do-able in a month. IIRC, Atlys uses HDMI transceivers, but the vMod-MIB doesn't . Will have to see if auto-detection can be done or not.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
