### ISSUE TITLE
Either remove or use debouncerBtnr block

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#63]
When compiling you get the following error;

```
WARNING:Xst:1290 - Hierarchical block <debouncerBtnr> is unconnected in block <hdmi2usb>.
```

**Comment by rohitk-singh** [comment]
"Right" button is currently unused, but will be used to switch to VGA input. My current code integrated with HDMI2USB uses this button for switching to VGA

**Comment by mithro** [comment]
Great! Assigning the bug to you :)

**Comment by mithro** [comment]
https://github.com/timvideos/HDMI2USB/issues/38

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
