### ISSUE TITLE
There are clock issues in testpattern generator

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#64]
@rohit91 Is this related to the more interesting test pattern you worked on?

```
WARNING:Timing:3159 - The DCM, testpattern_comp/patternClk_com/dcm_clkgen_inst, has the attribute DFS_OSCILLATOR_MODE not set to
   PHASE_FREQ_LOCK. No phase relationship exists between the input clock and CLKFX or CLKFX180 outputs of this DCM. Data paths between these
   clock domains must be constrained using FROM/TO constraints.
```

**Comment by rohitk-singh** [comment]
No, its not related to that. Its related to DCM_CLKGEN which has no phase relationship b/w clk (100MHz) and vga_pclk (65MHz). DCM_CLKGEN has no capability for phase relationship. If we require defined phase relationship, them we have to use either DCM_SP or PLL.

For my testpattern code, you will be getting a different warning related to VSYNC. Which can be ignored safely for now as VSYNC@60Hz is really slow compared to standard FPGA speeds. Although I'll try to remove it when free from VGA capture stuff.

**Comment by mithro** [comment]
https://github.com/timvideos/HDMI2USB/issues/38

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
