### ISSUE TITLE
Create build script which requires no GUI tools

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#7]
Makefile, cmake or other system which builds all of the following;
- CDC Firmware
- FGPA Firmware
- Tools needed to load firmware such as;
  - fxload
  - fgpa download tool???

**Comment by mithro** [comment]
Should support Windows + Linux (Ubuntu+RedHat Fedora). Ideally would also support Mac.

**Comment by mithro** [comment]
I believe this been mostly done by @jahanzeb 
- You can type `make` to build the FPGA firmware. @shenki wanted to restructure this in some way?
- I added a similar Makefile for the Cypress firmware but it requires a GUI environment to be available (but is still non-interactive).

**Comment by shenki** [comment]
Yeah, see the makefile branch in my repository:

 https://github.com/shenki/HDMI2USB/commit/400e65c7cdeec5f0df78f82bb7b9f39cf53605a8

It re-works @jahanzeb's work by doing dependency tracking. In theory, it will only trigger a rebuild if you change the part that needs to be rebuilt. Not sure how much, if at all, this helps in practice.

Note that this was done some time ago, and would need refreshing.

**Comment by mithro** [comment]
I think we now have the following bits;
- A "flash.sh" script which builds makestuff and loads the firmware onto the FPGA. https://github.com/timvideos/HDMI2USB/blob/master/tools/flash.sh
- Have a Makefile for cypress and after https://github.com/timvideos/HDMI2USB/issues/16 is completed, we won't need GUI tool or wine.
- No Windows / Mac support - but I don't think we really care?

@shenki - Are you able to rebase your Makefile stuff to the latest version?

If so, I think we can close this issue.

**Comment by mithro** [comment]
Fixed.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
