### ISSUE TITLE
Build system should parse the Xilinx tool output and generate stats

### ISSUE THREAD

**Issue by mithro** [timvideos/HDMI2USB-jahanzeb-firmware#77]
Start simple with things like;
- Number of warnings generated in each stage
- Output bit file size

Then move onto things like;
- The number of LUTs used
- Timing information

Then do all the above for each individual directory.

**Comment by shenki** [comment]
This tool will spit out stats by message type from the logs:

 https://github.com/leaflabs/xmsgs-tools.git

It will also do diffs between the xmsgs log files. We should plot these numbers to see changes between builds.

**Comment by mithro** [comment]
We should definitely start using this tool and help extend it.

**Comment by mithro** [comment]
See https://github.com/timvideos/HDMI2USB/wiki/Xilinx-Parsing-Tools too

**Comment by mithro** [comment]
https://github.com/timvideos/HDMI2USB-misoc-firmware/issues/62

**Comment by mithro** [comment]
This issue was moved to timvideos/HDMI2USB-misoc-firmware#152
