### ISSUE TITLE
Introduction of colourmake broke the build

### ISSUE THREAD

**Issue by shenki** [timvideos/HDMI2USB-jahanzeb-firmware#81]
@ajitmathew was attempting to build the firmware on his Ubuntu machine, and it failed with the following message:

```
/bin/sh: 7: Bad substitution
make: *** [syn] Error 2
```

We attempted to fix it by switching `/bin/sh` to `bash`, answering "No" to the following:

```
sudo dpkg-reconfigure dash
```

However he then saw another error:

```
/opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64/unwrapped/map: symbol lookup error: 
/opt/Xilinx/14.7/ISE_DS/ISE//lib/lin64/libPackSolver.so: undefined symbol:
make: *** [map] Error 127
```

Rebooting resolved this, and he was able to build the firmware.

It's not clear if the fix was the reboot, or switching `/bin/sh` to `bash`, or if both are required.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
