### ISSUE TITLE
Warning in edid_master_slave_hack

### ISSUE THREAD

**Issue by shenki** [timvideos/HDMI2USB-jahanzeb-firmware#89]
This looks like a real warning:

```
hdl/edid/edid_master_slave_hack.v" Line 112: Result of 8-bit expression is truncated to fit in 7-bit target.
```

The code looks like this, with the warning referring to the last line of this snippet:

```
wire [7:0] edid_byte_lcd;
reg [6:0] segments;

segments <= edid_byte_lcd;
```

8 does not fit into 7, as the warning tells us.

This blocks #38.

**Comment by mithro** [comment]
Closing this as the [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development.

**Comment by mithro** [comment]
The [HDMI2USB-jahanzeb-firmware](https://github.com/timvideos/HDMI2USB-jahanzeb-firmware) is no longer under development. 

All active development is now on the [HDMI2USB-misoc-firmware](https://github.com/timvideos/HDMI2USB-misoc-firmware) which supports both the [Atlys](https://hdmi2usb.tv/digilent-atlys/) and [Opsis](https://hdmi2usb.tv/numato-opsis/) boards and has loads of other new features!
