### ISSUE TITLE
Add PTZ support to uvc device

### ISSUE THREAD

**Issue by shenki** [timvideos/HDMI2USB-jahanzeb-firmware#95]
It appears that the v4l2 uvcvideo device can support PTZ controls, and the kernel has support for this: https://lkml.org/lkml/2014/7/8/837

We should add support to our uvc device, and make the fx2 firmware pass on the commands through to the serial board that does PTZ control.

**Comment by mithro** [comment]
This issue was moved to timvideos/HDMI2USB-misoc-firmware#150
